const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    USER_SIGNUP_SUCCESS: 'USER_SIGNUP_SUCCESS',
    USER_SIGNUP_FAIL: 'USER_SIGNUP_FAIL',
    USER_LOGOUT: 'USER_LOGOUT',
    GET_ONE_USER: 'GET_ONE_USER',
    EDIT_ONE_USER: 'EDIT_ONE_USER',
    CREATE_ONE_POSTS: 'CREATE_ONE_POSTS',
    GET_ONE_POSTS: 'GET_ONE_POSTS'





})

export default actionTypes;